/**
 * Anti-Ban Spintax Parser & Template Variable Engine
 * Supports nested spintax variations: {A|{B|C}} and dynamic template variables.
 */

export interface SpintaxVariables {
  name?: string;
  nama?: string;
  phone?: string;
  nomor?: string;
  time?: string;
  jam?: string;
  date?: string;
  tanggal?: string;
  [key: string]: string | undefined;
}

/**
 * Resolves template variables (e.g. {{name}}, {{time}}, {{date}})
 */
export function injectVariables(text: string, variables: SpintaxVariables = {}): string {
  const now = new Date();
  const defaultTime = new Intl.DateTimeFormat('id-ID', {
    timeZone: 'Asia/Jakarta',
    hour: '2-digit',
    minute: '2-digit',
  }).format(now);

  const defaultDate = new Intl.DateTimeFormat('id-ID', {
    timeZone: 'Asia/Jakarta',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(now);

  const resolvedVars: Record<string, string> = {
    name: variables.name || variables.nama || 'Kak',
    nama: variables.nama || variables.name || 'Kak',
    phone: variables.phone || variables.nomor || '',
    nomor: variables.nomor || variables.phone || '',
    time: variables.time || variables.jam || defaultTime,
    jam: variables.jam || variables.time || defaultTime,
    date: variables.date || variables.tanggal || defaultDate,
    tanggal: variables.tanggal || variables.date || defaultDate,
    ...variables,
  };

  return text.replace(/\{\{\s*([a-zA-Z0-9_-]+)\s*\}\}/g, (_match, key) => {
    return resolvedVars[key] !== undefined ? String(resolvedVars[key]) : _match;
  });
}

/**
 * Parses nested spintax syntax: {option1|option2|{nested1|nested2}}
 * Recursively resolves innermost choice groups until all spintax groups are resolved.
 */
export function parseSpintax(text: string, variables?: SpintaxVariables): string {
  if (!text) return '';

  // 1. Resolve template variables first
  let result = injectVariables(text, variables);

  // 2. Innermost spintax pattern: requires at least one pipe delimiter and no nested braces
  const spintaxRegex = /\{([^{}]*\|[^{}]*)\}/;

  while (spintaxRegex.test(result)) {
    result = result.replace(spintaxRegex, (_match, group) => {
      const options = group.split('|');
      const chosenIndex = Math.floor(Math.random() * options.length);
      return options[chosenIndex] || '';
    });
  }

  return result;
}

/**
 * Calculates the total number of unique combinations generated by a spintax string.
 */
export function countSpintaxVariations(text: string): number {
  if (!text) return 1;

  let current = text;
  const innermostRegex = /\{([^{}]*\|[^{}]*)\}/;

  // Track variation counts for collapsed blocks using token placeholders
  const tokenCounts = new Map<string, number>();
  let tokenCounter = 0;

  while (innermostRegex.test(current)) {
    current = current.replace(innermostRegex, (_match, group) => {
      const options = group.split('|');
      let groupTotal = 0;

      for (const opt of options) {
        // If an option contains a previously resolved token, multiply by its weight
        const tokensInOpt = opt.match(/__SPIN_TOKEN_(\d+)__/g);
        if (tokensInOpt && tokensInOpt.length > 0) {
          let optProduct = 1;
          for (const tok of tokensInOpt) {
            optProduct *= tokenCounts.get(tok) || 1;
          }
          groupTotal += optProduct;
        } else {
          groupTotal += 1;
        }
      }

      const tokenKey = `__SPIN_TOKEN_${tokenCounter++}__`;
      tokenCounts.set(tokenKey, groupTotal);
      return tokenKey;
    });
  }

  // Remaining top-level multiplied tokens
  const remainingTokens = current.match(/__SPIN_TOKEN_(\d+)__/g);
  if (!remainingTokens || remainingTokens.length === 0) return 1;

  let totalCombinations = 1;
  for (const tok of remainingTokens) {
    totalCombinations *= tokenCounts.get(tok) || 1;
  }

  return totalCombinations;
}

/**
 * Previews sample variations generated from a template
 */
export function previewSpintax(
  template: string,
  count = 3,
  sampleVariables: SpintaxVariables = { name: 'Budi' }
): { previews: string[]; totalVariations: number } {
  const previews: string[] = [];
  const totalVariations = countSpintaxVariations(template);

  for (let i = 0; i < count; i++) {
    previews.push(parseSpintax(template, sampleVariables));
  }

  return { previews, totalVariations };
}
